# Generated by Django 2.2.13 on 2021-04-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMAGE_upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enter_Subject_of_received_data_to_encrypt_file', models.CharField(max_length=50)),
                ('steganography_image', models.ImageField(upload_to='static/images/')),
            ],
        ),
    ]
